import 'package:flutter/material.dart';

/// Local demo posters under [assets/images/movies_demo/] (bundled; no network).
const String _kMoviesDemoDir = 'assets/images/movies_demo';

/// One file per demo title; order matches [kMockMovies] (24 rows). Use `0.png` … `23.png` in [movies_demo].
const List<String> _kMoviesDemoPosterFiles = [
  '0.png',
  '1.png',
  '2.png',
  '3.png',
  '4.png',
  '5.png',
  '6.png',
  '7.png',
  '8.png',
  '9.png',
  '10.png',
  '11.png',
  '12.png',
  '13.png',
  '14.png',
  '15.png',
  '16.png',
  '17.png',
  '18.png',
  '19.png',
  '20.png',
  '21.png',
  '22.png',
  '23.png',
];

String _moviesDemoPoster(int index) {
  if (index < 0 || index >= _kMoviesDemoPosterFiles.length) {
    return '$_kMoviesDemoDir/${_kMoviesDemoPosterFiles[0]}';
  }
  return '$_kMoviesDemoDir/${_kMoviesDemoPosterFiles[index]}';
}

/// Demo movie categories — real app will use playlist data.
class MockMovieCategory {
  const MockMovieCategory({required this.id, required this.name});

  final String id;
  final String name;
}

/// Demo / Xtream movie — poster art from [coverUrl] / [backdropUrl] when set.
/// Legacy [posterPrimary] fields are unused by UI; kept for hashing / tooling.
/// [streamUrl] is set for Xtream VOD; demo playback uses mock HLS URLs.
class MockMovie {
  const MockMovie({
    required this.id,
    required this.categoryId,
    required this.title,
    required this.year,
    required this.genre,
    required this.description,
    required this.duration,
    required this.posterPrimary,
    required this.posterSecondary,
    required this.backdropPrimary,
    required this.backdropSecondary,
    this.streamUrl,
    this.coverUrl,
    this.backdropUrl,
    this.cast,
    this.director,
    this.rating,
  });

  final String id;
  final String categoryId;
  final String title;
  final int year;
  final String genre;
  final String description;
  final String duration;
  final Color posterPrimary;
  final Color posterSecondary;
  final Color backdropPrimary;
  final Color backdropSecondary;
  final String? streamUrl;
  final String? coverUrl;
  final String? backdropUrl;

  /// From Xtream VOD row when the panel sends them (varies by provider).
  final String? cast;
  final String? director;
  final String? rating;
}

const List<MockMovieCategory> kMockMovieCategories = [
  MockMovieCategory(id: 'action', name: 'Action'),
  MockMovieCategory(id: 'drama', name: 'Drama'),
  MockMovieCategory(id: 'comedy', name: 'Comedy'),
  MockMovieCategory(id: 'trending', name: 'Trending'),
];

final List<MockMovie> kMockMovies = [
  MockMovie(
    id: 'a1',
    categoryId: 'action',
    title: 'Neon Run',
    year: 2023,
    genre: 'Action',
    description:
        'A courier races through a rain-soaked megacity when a single package pulls him into a corporate conspiracy.',
    duration: '2h 06m',
    posterPrimary: Color(0xFFE53935),
    posterSecondary: Color(0xFF5C1A1A),
    backdropPrimary: Color(0xFF8E1F2D),
    backdropSecondary: Color(0xFF12040A),
    coverUrl: _moviesDemoPoster(0),
    backdropUrl: _moviesDemoPoster(0),
    cast: 'Jordan Vale, Mira Santos, Eli Kwon',
    director: 'Alex Riven',
    rating: '7.2',
  ),
  MockMovie(
    id: 'a2',
    categoryId: 'action',
    title: 'Steel Horizon',
    year: 2021,
    genre: 'Action / Sci-Fi',
    description:
        'Ground crews defend a stranded orbital tether as tensions ignite between rival recovery teams.',
    duration: '1h 58m',
    posterPrimary: Color(0xFF1E88E5),
    posterSecondary: Color(0xFF0D2840),
    backdropPrimary: Color(0xFF123D6B),
    backdropSecondary: Color(0xFF050812),
    coverUrl: _moviesDemoPoster(1),
    backdropUrl: _moviesDemoPoster(1),
    cast: 'Chris Noland, Priya Menon, Theo Ward',
    director: 'Sam Okonkwo',
    rating: '6.9',
  ),
  MockMovie(
    id: 'a3',
    categoryId: 'action',
    title: 'Bone Deep',
    year: 2024,
    genre: 'Action · Thriller',
    description:
        'Two estranged siblings hunt the same syndicate from opposite sides of the law.',
    duration: '2h 11m',
    posterPrimary: Color(0xFF6D4C41),
    posterSecondary: Color(0xFF221712),
    backdropPrimary: Color(0xFF3E2723),
    backdropSecondary: Color(0xFF0A0605),
    coverUrl: _moviesDemoPoster(2),
    backdropUrl: _moviesDemoPoster(2),
    cast: 'Riley Fox, Omar Reyes, Lena Cho',
    director: 'Helena Márquez',
    rating: '7.5',
  ),
  MockMovie(
    id: 'a4',
    categoryId: 'action',
    title: 'Velvet Strike',
    year: 2019,
    genre: 'Action',
    description:
        'A choreographer-turned-operative uses performance halls as cover for covert extractions.',
    duration: '1h 49m',
    posterPrimary: Color(0xFFAD1457),
    posterSecondary: Color(0xFF2C0F1F),
    backdropPrimary: Color(0xFF6A1B3D),
    backdropSecondary: Color(0xFF0D0207),
    coverUrl: _moviesDemoPoster(3),
    backdropUrl: _moviesDemoPoster(3),
    cast: 'Sasha Lin, Devon Hart, Mateo Ruiz',
    director: 'Quinn Avery',
    rating: '6.4',
  ),
  MockMovie(
    id: 'a5',
    categoryId: 'action',
    title: 'Amber Circuit',
    year: 2022,
    genre: 'Action · Cyber',
    description:
        'Blackout sweeps the grid and a forensic electrician traces sabotage to a ghost address.',
    duration: '2h 01m',
    posterPrimary: Color(0xFFF9A825),
    posterSecondary: Color(0xFF3B2B08),
    backdropPrimary: Color(0xFF6D4C12),
    backdropSecondary: Color(0xFF0B0802),
    coverUrl: _moviesDemoPoster(4),
    backdropUrl: _moviesDemoPoster(4),
    cast: 'Nico Park, Ava Trent, Jun Becker',
    director: 'Morgan Ellis',
    rating: '7.0',
  ),
  MockMovie(
    id: 'a6',
    categoryId: 'action',
    title: 'Cold Relay',
    year: 2020,
    genre: 'Action',
    description:
        'Convoy drivers cross a frozen coast to deliver medicine before the storm shuts every road.',
    duration: '1h 54m',
    posterPrimary: Color(0xFF00897B),
    posterSecondary: Color(0xFF062822),
    backdropPrimary: Color(0xFF0E3C36),
    backdropSecondary: Color(0xFF020808),
    coverUrl: _moviesDemoPoster(5),
    backdropUrl: _moviesDemoPoster(5),
    cast: 'Elena Frost, Viktor Hale, Ida Singh',
    director: 'Jonas Pike',
    rating: '6.8',
  ),
  MockMovie(
    id: 'a7',
    categoryId: 'action',
    title: 'Glass Cartel',
    year: 2025,
    genre: 'Action · Crime',
    description:
        'Undercover agents pose as art movers to expose laundering in a city obsessed with auctions.',
    duration: '2h 04m',
    posterPrimary: Color(0xFF5E35B1),
    posterSecondary: Color(0xFF1D1230),
    backdropPrimary: Color(0xFF311B55),
    backdropSecondary: Color(0xFF05030A),
    coverUrl: _moviesDemoPoster(6),
    backdropUrl: _moviesDemoPoster(6),
    cast: 'Damon Cruz, Iris Bell, Frank Osei',
    director: 'Yuki Taneda',
    rating: '7.8',
  ),
  MockMovie(
    id: 'a8',
    categoryId: 'action',
    title: 'Skyline Siege',
    year: 2018,
    genre: 'Action',
    description:
        'A high-rise evacuation becomes a chess match between rescue teams and an unseen sniper.',
    duration: '1h 52m',
    posterPrimary: Color(0xFF546E7A),
    posterSecondary: Color(0xFF1A2329),
    backdropPrimary: Color(0xFF263238),
    backdropSecondary: Color(0xFF020304),
    coverUrl: _moviesDemoPoster(7),
    backdropUrl: _moviesDemoPoster(7),
    cast: 'Tara Miles, Ben Cho, Lucia Ortega',
    director: 'Derek Vaughn',
    rating: '6.6',
  ),
  MockMovie(
    id: 'd1',
    categoryId: 'drama',
    title: 'The Quiet Harbor',
    year: 2023,
    genre: 'Drama',
    description:
        'Returning siblings repair an old boathouse and reconstruct a childhood they remember differently.',
    duration: '2h 18m',
    posterPrimary: Color(0xFF0277BD),
    posterSecondary: Color(0xFF061826),
    backdropPrimary: Color(0xFF0D3C55),
    backdropSecondary: Color(0xFF02070A),
    coverUrl: _moviesDemoPoster(8),
    backdropUrl: _moviesDemoPoster(8),
    cast: 'Grace Holt, Peter Yam, Sofia Abboud',
    director: 'Nina Calder',
    rating: '7.4',
  ),
  MockMovie(
    id: 'd2',
    categoryId: 'drama',
    title: 'Paper Orchards',
    year: 2021,
    genre: 'Drama',
    description:
        'An archivist unseals letters that reroute her family’s farm through decades of unspoken bargains.',
    duration: '1h 59m',
    posterPrimary: Color(0xFF558B2F),
    posterSecondary: Color(0xFF1B240F),
    backdropPrimary: Color(0xFF2F4518),
    backdropSecondary: Color(0xFF060803),
    coverUrl: _moviesDemoPoster(9),
    backdropUrl: _moviesDemoPoster(9),
    cast: 'Mara Quinn, Ian Cole, Ruth Adeyemi',
    director: 'Paulo Ferreira',
    rating: '7.1',
  ),
  MockMovie(
    id: 'd3',
    categoryId: 'drama',
    title: 'Half-Light Avenue',
    year: 2022,
    genre: 'Drama',
    description:
        'Neighbors share a stoop and competing memories of the night the streetlights failed for good.',
    duration: '2h 05m',
    posterPrimary: Color(0xFF795548),
    posterSecondary: Color(0xFF241A16),
    backdropPrimary: Color(0xFF4A332A),
    backdropSecondary: Color(0xFF090605),
    coverUrl: _moviesDemoPoster(10),
    backdropUrl: _moviesDemoPoster(10),
    cast: 'Vera Lang, Omar Diaz, Kim Alvarez',
    director: 'Stefan Weber',
    rating: '6.9',
  ),
  MockMovie(
    id: 'd4',
    categoryId: 'drama',
    title: 'Salt of the Floorboards',
    year: 2019,
    genre: 'Drama',
    description:
        'A dancer rehearses in an empty theater while creditors circle the building’s deed.',
    duration: '1h 46m',
    posterPrimary: Color(0xFF6A1B9A),
    posterSecondary: Color(0xFF200A2B),
    backdropPrimary: Color(0xFF3A1261),
    backdropSecondary: Color(0xFF050208),
    coverUrl: _moviesDemoPoster(11),
    backdropUrl: _moviesDemoPoster(11),
    cast: 'Clara Voss, Malik Brooks, Jen Okada',
    director: 'Isabel Romero',
    rating: '7.3',
  ),
  MockMovie(
    id: 'd5',
    categoryId: 'drama',
    title: 'Winter Registry',
    year: 2024,
    genre: 'Drama',
    description:
        'A census clerk travels a shuttered valley and learns why entire towns declined to be counted.',
    duration: '2h 12m',
    posterPrimary: Color(0xFF78909C),
    posterSecondary: Color(0xFF242A2E),
    backdropPrimary: Color(0xFF455A64),
    backdropSecondary: Color(0xFF040506),
    coverUrl: _moviesDemoPoster(12),
    backdropUrl: _moviesDemoPoster(12),
    cast: 'Noah Pierce, Ada Okafor, Timur Shah',
    director: 'Eve Lindstrom',
    rating: '7.0',
  ),
  MockMovie(
    id: 'd6',
    categoryId: 'drama',
    title: 'Bridges on Tuesday',
    year: 2020,
    genre: 'Drama / Romance',
    description:
        'Two engineers alternate closing shifts on the same bridge and trade stories through logbooks.',
    duration: '1h 57m',
    posterPrimary: Color(0xFFBF360C),
    posterSecondary: Color(0xFF2D150C),
    backdropPrimary: Color(0xFF5E260E),
    backdropSecondary: Color(0xFF080302),
    coverUrl: _moviesDemoPoster(13),
    backdropUrl: _moviesDemoPoster(13),
    cast: 'Hannah Yu, Cole Trent, Rosa Vega',
    director: 'Markus Lind',
    rating: '6.7',
  ),
  MockMovie(
    id: 'c1',
    categoryId: 'comedy',
    title: 'Slightly Legal',
    year: 2023,
    genre: 'Comedy',
    description:
        'Mistaken identity at a courthouse leads to a week of judgements no one can appeal.',
    duration: '1h 44m',
    posterPrimary: Color(0xFFF4511E),
    posterSecondary: Color(0xFF3B1408),
    backdropPrimary: Color(0xFF7A2E12),
    backdropSecondary: Color(0xFF090302),
    coverUrl: _moviesDemoPoster(14),
    backdropUrl: _moviesDemoPoster(14),
    cast: 'Pat Kim, Jules Meyer, Dana Fox',
    director: 'Robbie Shaw',
    rating: '6.5',
  ),
  MockMovie(
    id: 'c2',
    categoryId: 'comedy',
    title: 'Cousin Algorithm',
    year: 2022,
    genre: 'Comedy',
    description:
        'A wedding app pairs guests by “compatibility,” igniting feuds between actual cousins.',
    duration: '1h 39m',
    posterPrimary: Color(0xFFFFCA28),
    posterSecondary: Color(0xFF3D3309),
    backdropPrimary: Color(0xFF806517),
    backdropSecondary: Color(0xFF0A0802),
    coverUrl: _moviesDemoPoster(15),
    backdropUrl: _moviesDemoPoster(15),
    cast: 'Zoe Patel, Andy Berg, Carla Munez',
    director: 'Felix Brandt',
    rating: '6.3',
  ),
  MockMovie(
    id: 'c3',
    categoryId: 'comedy',
    title: 'Lost & Founder',
    year: 2021,
    genre: 'Comedy',
    description:
        'Startup rivals accidentally move into the same co-working closet with one router between them.',
    duration: '1h 52m',
    posterPrimary: Color(0xFF00ACC1),
    posterSecondary: Color(0xFF063239),
    backdropPrimary: Color(0xFF0E5460),
    backdropSecondary: Color(0xFF020708),
    coverUrl: _moviesDemoPoster(16),
    backdropUrl: _moviesDemoPoster(16),
    cast: 'Wes Amir, Tina Gould, Raj Kapoor',
    director: 'Casey Bloom',
    rating: '6.8',
  ),
  MockMovie(
    id: 'c4',
    categoryId: 'comedy',
    title: 'The Heist Rehearsal',
    year: 2024,
    genre: 'Comedy / Heist',
    description:
        'Community theater actors rehearse a fake robbery that the city mistakes for breaking news.',
    duration: '1h 48m',
    posterPrimary: Color(0xFF8E24AA),
    posterSecondary: Color(0xFF270F30),
    backdropPrimary: Color(0xFF4E1D60),
    backdropSecondary: Color(0xFF060208),
    coverUrl: _moviesDemoPoster(17),
    backdropUrl: _moviesDemoPoster(17),
    cast: 'Brett Lane, Nora Sims, Miguel Costa',
    director: 'Daria Owens',
    rating: '7.1',
  ),
  MockMovie(
    id: 'c5',
    categoryId: 'comedy',
    title: 'Spoiler Season',
    year: 2019,
    genre: 'Comedy',
    description:
        'Book club bylaws require spoilers on page one, testing friendships and marriages.',
    duration: '1h 36m',
    posterPrimary: Color(0xFF43A047),
    posterSecondary: Color(0xFF122614),
    backdropPrimary: Color(0xFF245427),
    backdropSecondary: Color(0xFF030602),
    coverUrl: _moviesDemoPoster(18),
    backdropUrl: _moviesDemoPoster(18),
    cast: 'Meg Doyle, Steve Park, Uma Iyer',
    director: 'Harriet Cole',
    rating: '6.2',
  ),
  MockMovie(
    id: 'c6',
    categoryId: 'comedy',
    title: 'Accidental Influencer',
    year: 2020,
    genre: 'Comedy',
    description:
        'A shy archivist uploads the wrong folder and becomes famous for “silent reviews.”',
    duration: '1h 41m',
    posterPrimary: Color(0xFFEC407A),
    posterSecondary: Color(0xFF3A1022),
    backdropPrimary: Color(0xFF7A2445),
    backdropSecondary: Color(0xFF070205),
    coverUrl: _moviesDemoPoster(19),
    backdropUrl: _moviesDemoPoster(19),
    cast: 'Lily Tran, Greg Moss, Priya Nair',
    director: 'Owen Blake',
    rating: '6.6',
  ),
  MockMovie(
    id: 't1',
    categoryId: 'trending',
    title: 'Echo Atlas',
    year: 2025,
    genre: 'Thriller',
    description:
        'Cartographers race to finish an impossible map before a coastal rail line is decommissioned.',
    duration: '2h 03m',
    posterPrimary: Color(0xFF3949AB),
    posterSecondary: Color(0xFF101633),
    backdropPrimary: Color(0xFF1F276A),
    backdropSecondary: Color(0xFF02030A),
    coverUrl: _moviesDemoPoster(20),
    backdropUrl: _moviesDemoPoster(20),
    cast: 'Felix Grant, Nina Cho, Hugo Silva',
    director: 'Laura Finch',
    rating: '7.6',
  ),
  MockMovie(
    id: 't2',
    categoryId: 'trending',
    title: 'Afterglow District',
    year: 2024,
    genre: 'Mystery',
    description:
        'Power flickers isolate a nightlife strip where every neon sign prints the same timestamp.',
    duration: '1h 55m',
    posterPrimary: Color(0xFFFF7043),
    posterSecondary: Color(0xFF3D1A0F),
    backdropPrimary: Color(0xFF7A3A24),
    backdropSecondary: Color(0xFF070201),
    coverUrl: _moviesDemoPoster(21),
    backdropUrl: _moviesDemoPoster(21),
    cast: 'Aria Cole, Dean Marks, Mei Wong',
    director: 'Victor Hahn',
    rating: '7.2',
  ),
  MockMovie(
    id: 't3',
    categoryId: 'trending',
    title: 'Parallel Guesthouse',
    year: 2023,
    genre: 'Drama / Sci-Fi',
    description:
        'Travelers discover their rental has a hallway that opens into two different weather systems.',
    duration: '2h 09m',
    posterPrimary: Color(0xFF26A69A),
    posterSecondary: Color(0xFF0A2A24),
    backdropPrimary: Color(0xFF135349),
    backdropSecondary: Color(0xFF020706),
    coverUrl: _moviesDemoPoster(22),
    backdropUrl: _moviesDemoPoster(22),
    cast: 'Jonah Reed, Pia Lorenz, Sam Dupont',
    director: 'Claire Dubois',
    rating: '7.4',
  ),
  MockMovie(
    id: 't4',
    categoryId: 'trending',
    title: 'Signal Choir',
    year: 2022,
    genre: 'Music / Drama',
    description:
        'An outage silences phones, and a rooftop choir becomes the only emergency broadcast.',
    duration: '1h 51m',
    posterPrimary: Color(0xFFAB47BC),
    posterSecondary: Color(0xFF2B1231),
    backdropPrimary: Color(0xFF5B2A66),
    backdropSecondary: Color(0xFF060207),
    coverUrl: _moviesDemoPoster(23),
    backdropUrl: _moviesDemoPoster(23),
    cast: 'Renee Park, Caleb Stone, Ines Ruiz',
    director: 'Marcus Webb',
    rating: '7.0',
  ),
];

List<MockMovie> mockMoviesForCategory(String categoryId) {
  return kMockMovies
      .where((m) => m.categoryId == categoryId)
      .toList(growable: false);
}
